# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {E:/SJTU/2020 Fall/VE370/Project2/project_2_group_2/project_2_group_2.cache/wt} [current_project]
set_property parent.project_path {E:/SJTU/2020 Fall/VE370/Project2/project_2_group_2/project_2_group_2.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {e:/SJTU/2020 Fall/VE370/Project2/project_2_group_2/project_2_group_2.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {E:/SJTU/2020 Fall/VE370/Project2/project_2_group_2/project_2_group_2.srcs/sources_1/new/ALU.v}
  {E:/SJTU/2020 Fall/VE370/Project2/project_2_group_2/project_2_group_2.srcs/sources_1/new/ALUControl.v}
  {E:/SJTU/2020 Fall/VE370/Project2/project_2_group_2/project_2_group_2.srcs/sources_1/new/Adder.v}
  {E:/SJTU/2020 Fall/VE370/Project2/project_2_group_2/project_2_group_2.srcs/sources_1/new/Control.v}
  {E:/SJTU/2020 Fall/VE370/Project2/project_2_group_2/project_2_group_2.srcs/sources_1/new/EXMEM.v}
  {E:/SJTU/2020 Fall/VE370/Project2/project_2_group_2/project_2_group_2.srcs/sources_1/new/Equal.v}
  {E:/SJTU/2020 Fall/VE370/Project2/project_2_group_2/project_2_group_2.srcs/sources_1/new/Forward_Unit.v}
  {E:/SJTU/2020 Fall/VE370/Project2/project_2_group_2/project_2_group_2.srcs/sources_1/new/Hazard_Detection_Unit.v}
  {E:/SJTU/2020 Fall/VE370/Project2/project_2_group_2/project_2_group_2.srcs/sources_1/new/IDEX.v}
  {E:/SJTU/2020 Fall/VE370/Project2/project_2_group_2/project_2_group_2.srcs/sources_1/new/IFID.v}
  {E:/SJTU/2020 Fall/VE370/Project2/project_2_group_2/project_2_group_2.srcs/sources_1/new/MEMWB.v}
  {E:/SJTU/2020 Fall/VE370/Project2/project_2_group_2/project_2_group_2.srcs/sources_1/new/PC.v}
  {E:/SJTU/2020 Fall/VE370/Project2/project_2_group_2/project_2_group_2.srcs/sources_1/new/add.v}
  {E:/SJTU/2020 Fall/VE370/Project2/project_2_group_2/project_2_group_2.srcs/sources_1/new/buffer.v}
  {E:/SJTU/2020 Fall/VE370/Project2/project_2_group_2/project_2_group_2.srcs/sources_1/new/dataMemory.v}
  {E:/SJTU/2020 Fall/VE370/Project2/project_2_group_2/project_2_group_2.srcs/sources_1/new/divider.v}
  {E:/SJTU/2020 Fall/VE370/Project2/project_2_group_2/project_2_group_2.srcs/sources_1/new/instructionMem.v}
  {E:/SJTU/2020 Fall/VE370/Project2/project_2_group_2/project_2_group_2.srcs/sources_1/new/mux2.v}
  {E:/SJTU/2020 Fall/VE370/Project2/project_2_group_2/project_2_group_2.srcs/sources_1/new/mux232.v}
  {E:/SJTU/2020 Fall/VE370/Project2/project_2_group_2/project_2_group_2.srcs/sources_1/new/mux24.v}
  {E:/SJTU/2020 Fall/VE370/Project2/project_2_group_2/project_2_group_2.srcs/sources_1/new/mux25.v}
  {E:/SJTU/2020 Fall/VE370/Project2/project_2_group_2/project_2_group_2.srcs/sources_1/new/mux4.v}
  {E:/SJTU/2020 Fall/VE370/Project2/project_2_group_2/project_2_group_2.srcs/sources_1/new/mux432.v}
  {E:/SJTU/2020 Fall/VE370/Project2/project_2_group_2/project_2_group_2.srcs/sources_1/new/muxControl.v}
  {E:/SJTU/2020 Fall/VE370/Project2/project_2_group_2/project_2_group_2.srcs/sources_1/new/onebitALU.v}
  {E:/SJTU/2020 Fall/VE370/Project2/project_2_group_2/project_2_group_2.srcs/sources_1/new/project2pipeline.v}
  {E:/SJTU/2020 Fall/VE370/Project2/project_2_group_2/project_2_group_2.srcs/sources_1/new/registers.v}
  {E:/SJTU/2020 Fall/VE370/Project2/project_2_group_2/project_2_group_2.srcs/sources_1/new/ringCounter.v}
  {E:/SJTU/2020 Fall/VE370/Project2/project_2_group_2/project_2_group_2.srcs/sources_1/new/shiftLeft16.v}
  {E:/SJTU/2020 Fall/VE370/Project2/project_2_group_2/project_2_group_2.srcs/sources_1/new/shiftLeft26.v}
  {E:/SJTU/2020 Fall/VE370/Project2/project_2_group_2/project_2_group_2.srcs/sources_1/new/signExend.v}
  {E:/SJTU/2020 Fall/VE370/Project2/project_2_group_2/project_2_group_2.srcs/sources_1/new/ssd.v}
  {E:/SJTU/2020 Fall/VE370/Project2/project_2_group_2/project_2_group_2.srcs/sources_1/new/p2implement.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{E:/SJTU/2020 Fall/VE370/Project2/project_2_group_2/project_2_group_2.srcs/constrs_1/new/constraint.xdc}}
set_property used_in_implementation false [get_files {{E:/SJTU/2020 Fall/VE370/Project2/project_2_group_2/project_2_group_2.srcs/constrs_1/new/constraint.xdc}}]


synth_design -top p2implement -part xc7a35tcpg236-1


write_checkpoint -force -noxdef p2implement.dcp

catch { report_utilization -file p2implement_utilization_synth.rpt -pb p2implement_utilization_synth.pb }
